server:
  port: 8888
spring:
  application:
    name: ribbon-server
eureka:
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/
security:
  user:
    name: xiaoy
    password: xiaoy

service:
  path: http://microservice-provide-user/user/
