spring:
  application:
    name: eureka-highAvailablitity

---
server:
  port: 8808
spring:
  profiles: peer1
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8809/eureka/
---
server:
  port: 8809
spring:
  profiles: peer2
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8808/eureka/

