spring:
  application:
    name: discovery-eureka
server:
  port: 8762
eureka:
  instance:
      hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  basic:
    enabled: true
  user:
    name: user
    password: password


